#!/usr/bin/env bash
# Discover four free contiguous-ish ports for Decipher and write to .env.
# Per spec §2: starting ranges deliberately in high 5-digit space.
set -euo pipefail

find_free_port() {
  local start=$1
  while lsof -iTCP:"$start" -sTCP:LISTEN -n -P >/dev/null 2>&1; do
    start=$((start + 1))
  done
  echo "$start"
}

DB_PORT=$(find_free_port 55432)
API_PORT=$(find_free_port 58080)
WEB_PORT=$(find_free_port 55173)
MAIL_PORT=$(find_free_port 58025)

ENV_FILE="$(cd "$(dirname "$0")/.." && pwd)/.env"

cat > "$ENV_FILE" <<EOF
# Decipher local environment (generated by scripts/find_ports.sh)
DECIPHER_DB_PORT=$DB_PORT
DECIPHER_API_PORT=$API_PORT
DECIPHER_WEB_PORT=$WEB_PORT
DECIPHER_MAIL_PORT=$MAIL_PORT

POSTGRES_DB=decipher
POSTGRES_USER=decipher
POSTGRES_PASSWORD=decipher_local_dev

JWT_SECRET=change-me-in-prod
ANTHROPIC_API_KEY=

STRIPE_SECRET_KEY=
STRIPE_WEBHOOK_SECRET=

MAIL_FROM=audit@decipher.local
EOF

echo "Wrote $ENV_FILE"
echo "  DB   $DB_PORT"
echo "  API  $API_PORT"
echo "  WEB  $WEB_PORT"
echo "  MAIL $MAIL_PORT"
